name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    name: Build Deploy
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Image
        run: |
          docker build -t $DOCKERHUB_USERNAME/vehicle-resale-api:latest .

      - name: Login Docker Hub
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Push Image
        run: |
          docker push $DOCKERHUB_USERNAME/vehicle-resale-api:latest

      - name: Deploy no GKE
        run: |
          gcloud container clusters get-credentials fiap-postech --zone us-central1-a
          kubectl apply -f k8s/ -n vehicle-resale
